{% set name = "python-ipware" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-ipware-{{ version }}.tar.gz
  sha256: a52757123c718342f74b16ab2d9d4a531888d69d10b8197c073164635df0a13b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.7

test:
  imports:
    - python_ipware
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A Python package to retrieve user's IP address
  dev_url: https://github.com/un33k/python-ipware
  home: https://pypi.org/project/python-ipware/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - swainn
